/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>
#include <errno.h>

/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#ifndef _WIN32
#include <unistd.h>
#endif

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif


/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
static yyconst short int yy_accept[234] =
    {   0,
        0,    0,   55,   53,   52,   48,    8,   51,    5,   53,
       13,   14,    5,    4,   18,   35,    5,   43,   43,    9,
        2,   12,    2,   46,   46,   46,   46,   46,   46,   36,
       37,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   15,   53,   16,   52,    3,   51,    0,
       49,   51,    6,    0,   47,   47,    0,   43,    0,    2,
       46,   46,   46,   46,   46,   46,   11,   46,   46,   46,
       46,   46,   46,   46,   24,   46,   46,   46,   46,   46,
       46,   46,   46,    7,   49,   50,   47,   45,   44,   46,
       46,   33,   46,   46,   46,   46,   46,   46,   46,   46,

       46,   27,   46,   10,   46,   46,   46,   46,   46,   46,
        0,   46,   46,   46,   46,   46,    1,   10,   46,   46,
       46,   25,   46,   46,   46,   46,   42,   46,   46,   23,
       17,   46,    0,   46,    1,   46,   30,   46,   46,   46,
       29,   19,   46,   46,   46,   46,   46,   46,   46,   26,
       45,   46,   46,   46,   46,   46,   10,   46,   46,   46,
       46,   28,   10,   46,   46,   46,   46,   46,   46,   20,
       46,   46,   46,   46,   46,   34,   46,   32,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       22,   46,   46,   46,   46,   46,   21,   46,   46,   46,

       31,   46,   46,   38,   46,   46,   40,   46,   46,   46,
       46,   46,   46,   39,   41,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   46,
       46,   46,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   17,
       17,   17,   17,   17,   17,   17,   17,    1,   18,   19,
       20,   21,    1,    1,   22,   23,   24,   23,   25,   26,
       27,   27,   28,   27,   27,   29,   27,   30,   27,   31,
       27,   32,   27,   33,   27,   27,   27,   34,   27,   27,
       35,    2,   36,   37,   38,    1,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   27,   48,   49,   50,   51,
       52,   53,   27,   54,   55,   56,   57,   58,   59,   60,
       61,   27,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    1,    1,    5,    4,    3,    3,
        3,    3,    3,    3,    4,    4,    4,    4,    4,    4,
        6,    4,    4,    6,    4,    6,    4,    4,    4,    4,
        4,    1,    7,    1
    } ;

static yyconst short int yy_base[270] =
    {   0,
        0,    0,  375,  376,  372,  376,  353,   62,  376,  365,
      376,  376,   56,  376,  376,  376,   58,   60,   64,  376,
      351,  350,  349,    0,  329,  324,  312,  322,  310,  327,
      376,   18,  313,  309,   26,  308,   38,  302,  315,  301,
      310,  303,  308,  376,  290,  376,  350,  376,   80,  346,
      345,  344,  376,   69,   77,    0,   74,   79,    0,  376,
        0,  299,  288,  299,  306,  287,  376,  291,  299,  302,
      283,  284,  282,  283,    0,  283,  279,  285,  277,  278,
      284,  283,  282,  376,  323,  376,    0,   81,    0,    0,
      272,  304,  274,  282,  280,  273,  282,  265,  279,  275,

      274,    0,  267,   76,  266,  257,  266,  257,  269,  261,
      298,    0,  265,  253,  250,   73,    0,  281,  256,  248,
      253,    0,  250,  256,  243,  237,    0,  233,  232,    0,
        0,  236,   87,    0,    0,  221,    0,  220,  220,  211,
        0,    0,  216,  213,  201,  196,  199,  188,  190,    0,
       91,    0,  192,  171,  172,  168,  191,  156,  164,  148,
      160,    0,  171,    0,  130,  144,  140,  127,  129,    0,
      123,  111,  119,  100,    0,    0,   97,    0,   85,   89,
       83,   99,   94,   84,    0,   90,   93,   75,   74,   77,
        0,   72,    0,   72,   73,   66,    0,   65,   59,    0,

        0,   58,   73,    0,   72,    0,    0,   59,   58,    0,
       49,   13,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  376,  376,  143,  150,  155,  161,  165,  172,  177,
      182,  186,  190,  194,  198,  202,  206,  210,  214,  218,
      222,  226,  230,  234,  238,  242,  246,  250,  254,  258,
      262,  266,  270,  274,  278,  282,  286,  290,  294
    } ;

static yyconst short int yy_def[270] =
    {   0,
      233,    1,  233,  233,  233,  233,  233,  234,  233,  233,
      233,  233,  235,  233,  233,  233,  235,  233,  233,  233,
      233,  233,  233,  236,  236,  236,  236,  236,  236,  233,
      233,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  236,  233,  233,  233,  233,  233,  234,  237,
      237,  238,  233,  235,  235,  239,  233,  233,  240,  233,
      241,  241,  241,  241,  241,  241,  233,  241,  241,  241,
      241,  241,  241,  241,  241,  241,  241,  241,  241,  241,
      241,  241,  241,  233,  237,  233,  239,  233,  240,  242,
      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,

      242,  242,  242,  242,  242,  242,  242,  242,  242,  242,
      233,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  243,  233,  244,  244,  244,  244,  244,  244,  244,
      244,  244,  244,  244,  244,  244,  244,  244,  244,  244,
      233,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  246,  246,  246,  246,  246,  246,  246,
      246,  246,  246,  246,  247,  247,  247,  247,  247,  247,
      247,  247,  247,  247,  248,  248,  248,  248,  248,  248,
      248,  248,  249,  249,  249,  249,  249,  249,  249,  250,

      250,  250,  250,  250,  250,  251,  251,  251,  251,  252,
      252,  252,  253,  253,  253,  254,  255,  256,  257,  258,
      259,  260,  261,  262,  263,  264,  265,  266,  267,  268,
      269,  233,    0,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233
    } ;

static yyconst short int yy_nxt[441] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   14,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   24,   24,   24,   25,   24,   24,   24,   26,
       27,   28,   29,   24,   30,   31,    4,    4,   24,   32,
       33,   34,   35,   36,   24,   24,   37,   24,   24,   24,
       38,   24,   24,   39,   40,   41,   24,   42,   43,   24,
       24,   44,   45,   46,   50,   55,   51,   55,  215,   68,
       55,   69,   56,   57,   72,   58,   58,   57,   55,   58,
       58,   75,   50,   55,   51,   73,   55,   76,   77,   88,
       88,   55,   57,   59,   58,   58,   88,   88,   52,  125,

      138,  139,  151,  151,  214,  111,  151,  151,  212,  211,
      209,  208,   52,  207,  205,   52,   52,   52,  126,   59,
      204,  203,   59,  202,   52,  201,  199,  198,  197,  196,
       52,  195,  194,   52,  192,   52,  191,  190,  189,  188,
      187,  186,   52,   49,   49,   49,   49,   49,   49,   49,
       54,  184,   54,   54,   54,   54,   54,   61,   61,  183,
       61,   50,   50,   50,   50,   52,  182,   52,   52,   52,
       52,   52,   87,  181,   87,   87,   87,   87,   87,   89,
      180,  179,  178,   89,   90,   90,  177,   90,  112,  112,
      176,  112,  134,  134,  174,  134,  152,  152,  173,  152,

      164,  164,  172,  164,  175,  175,  171,  175,  185,  185,
      170,  185,  193,  193,  169,  193,  200,  200,  168,  200,
      206,  206,  167,  206,  210,  210,  166,  210,  213,  213,
      165,  213,  216,  216,  163,  216,  217,  217,  162,  217,
      218,  218,  161,  218,  219,  219,  160,  219,  220,  220,
      159,  220,  221,  221,  158,  221,  222,  222,  157,  222,
      223,  223,  156,  223,  224,  224,  155,  224,  225,  225,
      154,  225,  226,  226,  153,  226,  227,  227,  150,  227,
      228,  228,  149,  228,  229,  229,  148,  229,  230,  230,
      147,  230,  231,  231,  146,  231,  232,  232,  145,  232,

      144,  143,  142,  141,  140,  137,  136,  135,  133,  132,
      131,  130,  129,  128,  127,  124,  123,  122,  121,  120,
      119,  118,  117,  116,  115,  114,  113,   85,  110,  109,
      108,  107,  106,  105,  104,  103,  102,  101,  100,   99,
       98,   97,   96,   95,   94,   93,   92,   91,   86,   85,
       85,   47,   84,   83,   82,   81,   80,   79,   78,   74,
       71,   70,   67,   66,   65,   64,   63,   62,   60,   48,
       60,   53,   48,   47,  233,    3,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233
    } ;

static yyconst short int yy_chk[441] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    8,   13,    8,   17,  212,   32,
       13,   32,   17,   18,   35,   18,   18,   19,   54,   19,
       19,   37,   49,   54,   49,   35,   55,   37,   37,   57,
       57,   55,   58,   18,   58,   58,   88,   88,    8,  104,

      116,  116,  133,  133,  211,   88,  151,  151,  209,  208,
      205,  203,    8,  202,  199,    8,   49,    8,  104,   18,
      198,  196,   18,  195,    8,  194,  192,  190,  189,  188,
       49,  187,  186,   49,  184,   49,  183,  182,  181,  180,
      179,  177,   49,  234,  234,  234,  234,  234,  234,  234,
      235,  174,  235,  235,  235,  235,  235,  236,  236,  173,
      236,  237,  237,  237,  237,  238,  172,  238,  238,  238,
      238,  238,  239,  171,  239,  239,  239,  239,  239,  240,
      169,  168,  167,  240,  241,  241,  166,  241,  242,  242,
      165,  242,  243,  243,  163,  243,  244,  244,  161,  244,

      245,  245,  160,  245,  246,  246,  159,  246,  247,  247,
      158,  247,  248,  248,  157,  248,  249,  249,  156,  249,
      250,  250,  155,  250,  251,  251,  154,  251,  252,  252,
      153,  252,  253,  253,  149,  253,  254,  254,  148,  254,
      255,  255,  147,  255,  256,  256,  146,  256,  257,  257,
      145,  257,  258,  258,  144,  258,  259,  259,  143,  259,
      260,  260,  140,  260,  261,  261,  139,  261,  262,  262,
      138,  262,  263,  263,  136,  263,  264,  264,  132,  264,
      265,  265,  129,  265,  266,  266,  128,  266,  267,  267,
      126,  267,  268,  268,  125,  268,  269,  269,  124,  269,

      123,  121,  120,  119,  118,  115,  114,  113,  111,  110,
      109,  108,  107,  106,  105,  103,  101,  100,   99,   98,
       97,   96,   95,   94,   93,   92,   91,   85,   83,   82,
       81,   80,   79,   78,   77,   76,   74,   73,   72,   71,
       70,   69,   68,   66,   65,   64,   63,   62,   52,   51,
       50,   47,   45,   43,   42,   41,   40,   39,   38,   36,
       34,   33,   30,   29,   28,   27,   26,   25,   23,   22,
       21,   10,    7,    5,    3,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,

      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233,
      233,  233,  233,  233,  233,  233,  233,  233,  233,  233
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scannerDecaf.l"
#define INITIAL 0
#line 2 "scannerDecaf.l"
#include  <cstdio>
#include  <cstdlib>
#include  <string>
#include  <string.h>
#include <vector>
#include "VarObject.h"
#include <signal.h>
using  namespace  std;
#include "Nodo.h"

#include "parserDecaf.tab.h"   //  output  of  bison on  example1.y

void yyerror(const char *);
int  yyparse(void);
void addRow(int len, const char *token, char *value);
void printTable();
static char* itostr(int d);
static char* ftostr(double d);
int num_words = 0;
int num_caracteres = 1;
int num_lines=1;
int tableInt[1000][2];
const char* table[1000][2];

#line 572 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 84 "scannerDecaf.l"




#line 739 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 234 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 376 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 88 "scannerDecaf.l"
{addRow(yyleng,"BOOLEAN",yytext);yylval.boolValue= strdup(yytext);return BOOLEAN;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 90 "scannerDecaf.l"
{addRow(yyleng,"OP_REL",yytext);return OP_REL;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 92 "scannerDecaf.l"
{addRow(yyleng,"OP_IGUALDAD",yytext);return OP_IGUALDAD;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 94 "scannerDecaf.l"
{addRow(yyleng,"SUM_RESTA",yytext);return SUM_RESTA;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 96 "scannerDecaf.l"
{addRow(yyleng,"MUL_DIV_MOD",yytext);return MUL_DIV_MOD;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "scannerDecaf.l"
{addRow(yyleng,"LOG_AND",yytext);return LOG_AND;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 100 "scannerDecaf.l"
{addRow(yyleng,"LOG_OR",yytext);return LOG_OR;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 102 "scannerDecaf.l"
{addRow(yyleng,"NOT",yytext);return NOT;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 104 "scannerDecaf.l"
{addRow(yyleng,"SEMICOLON",yytext);return SEMICOLON;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 106 "scannerDecaf.l"
{addRow(yyleng,"TYPE",yytext);yylval.tipo = strdup(yytext);return TYPE;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 108 "scannerDecaf.l"
{addRow(yyleng,"SQRBRACKET",yytext);return SQRBRACKET;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 110 "scannerDecaf.l"
{addRow(yyleng,"EQUALS",yytext);return EQUALS;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "scannerDecaf.l"
{addRow(yyleng,"OPENPAR",yytext);return OPENPAR;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 114 "scannerDecaf.l"
{addRow(yyleng,"CLOSEPAR",yytext);return CLOSEPAR;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 116 "scannerDecaf.l"
{addRow(yyleng,"OPENBRA",yytext);return OPENBRA;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 118 "scannerDecaf.l"
{addRow(yyleng,"CLOSEBRA",yytext);return CLOSEBRA;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "scannerDecaf.l"
{addRow(yyleng,"VOID",yytext);yylval.voidT = strdup(yytext);return VOID;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 122 "scannerDecaf.l"
{addRow(yyleng,"COMMA",yytext);return COMMA;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 124 "scannerDecaf.l"
{addRow(yyleng,"CLASS",yytext);return CLASS;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 126 "scannerDecaf.l"
{addRow(yyleng,"EXTENDS",yytext);return EXTENDS;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 128 "scannerDecaf.l"
{addRow(yyleng,"IMPLEMENTS",yytext);return IMPLEMENTS;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 130 "scannerDecaf.l"
{addRow(yyleng,"INTERFACE",yytext);return INTERFACE;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 132 "scannerDecaf.l"
{addRow(yyleng,"THIS",yytext);return THIS;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 134 "scannerDecaf.l"
{addRow(yyleng,"IF",yytext);return IF;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 136 "scannerDecaf.l"
{addRow(yyleng,"ELSE",yytext);return ELSE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 138 "scannerDecaf.l"
{addRow(yyleng,"WHILE",yytext);return WHILE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 140 "scannerDecaf.l"
{addRow(yyleng,"THIS",yytext);return FOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 142 "scannerDecaf.l"
{addRow(yyleng,"RETURN",yytext);return RETURN;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 144 "scannerDecaf.l"
{addRow(yyleng,"BREAK",yytext);return BREAK;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 146 "scannerDecaf.l"
{addRow(yyleng,"PRINT",yytext);return PRINT;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 148 "scannerDecaf.l"
{addRow(yyleng,"READINT",yytext);return READINT;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 150 "scannerDecaf.l"
{addRow(yyleng,"READLINE",yytext);return READLINE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 152 "scannerDecaf.l"
{addRow(yyleng,"NEW",yytext);return NEW;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 154 "scannerDecaf.l"
{addRow(yyleng,"NEWARRAY",yytext);return NEWARRAY;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 156 "scannerDecaf.l"
{addRow(yyleng,"THIS",yytext);return POINT;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 158 "scannerDecaf.l"
{addRow(yyleng,"OPENSQR",yytext);return OPENSQR;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 160 "scannerDecaf.l"
{addRow(yyleng,"CLOSESQR",yytext);return CLOSESQR;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 162 "scannerDecaf.l"
{addRow(yyleng,"INTCONST",yytext);return INTCONST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 164 "scannerDecaf.l"
{addRow(yyleng,"DOUBLECONST",yytext);return DOUBLECONST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 166 "scannerDecaf.l"
{addRow(yyleng,"BOOLCONST",yytext);return BOOLCONST;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 168 "scannerDecaf.l"
{addRow(yyleng,"STRCONST",yytext);return STRCONST;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 170 "scannerDecaf.l"
{addRow(yyleng,"NULL",yytext);yylval.nullValue = strdup(yytext);return Null;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 172 "scannerDecaf.l"
{addRow(yyleng,"INT",yytext);yylval.int_val = strdup(yytext);return INT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 174 "scannerDecaf.l"
{addRow(yyleng,"HEX",yytext);yylval.str_val = new string(yytext);return HEX;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 176 "scannerDecaf.l"
{addRow(yyleng,"FLOAT",yytext);yylval.double_val = strdup(yytext);return FLOAT;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 178 "scannerDecaf.l"
{addRow(yyleng,"IDENTIFIER",yytext);yylval.id = strdup(yytext);return IDENTIFIER;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 180 "scannerDecaf.l"
{num_caracteres+=yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 182 "scannerDecaf.l"
{num_caracteres=1; num_lines++;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 184 "scannerDecaf.l"
{printf("Secuencia de escape ilegal en linea %d y columna %d\n",num_lines,num_caracteres);num_caracteres+=yyleng;exit(0);}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 186 "scannerDecaf.l"
{addRow(yyleng,"STRING",yytext);yylval.stringValue = strdup(yytext);return STRING;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 188 "scannerDecaf.l"
{printf("STRING no cerrado en linea %d y columna %d\n",num_lines,num_caracteres);exit(0);}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 192 "scannerDecaf.l"
{num_caracteres+=yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 194 "scannerDecaf.l"
{printf("Caracter ilegal <%s> en linea %d y columna %d\n",yytext,num_lines,num_caracteres);num_caracteres+=yyleng;exit(0);}//token ilegal
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 196 "scannerDecaf.l"
ECHO;
	YY_BREAK
#line 1092 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 234 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 234 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 233);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef _WIN32
#include <unistd.h>
#else
#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 196 "scannerDecaf.l"

void  yyerror(const char* str) {
    printf("Parsing error en linea %d , columna %d\n",num_lines,num_caracteres);
    exit(0);
}
int  yywrap(void) {}

void addRow(int len, const char *token, char *value){
      char *str = (char*)malloc(strlen(value)+1);
      if(str != NULL) strcpy(str,value);

      tableInt[num_words][0]=num_lines;
      tableInt[num_words][1]=num_caracteres;
      table[num_words][0]=token;
      table[num_words][1]=str;
      num_words++;
      num_caracteres+=len;
}

void printTable(){
  printf("\nLine     Column     Token           Value\n");
  /* for(int i=0; i<num_words;i++){
      printf("%d       ",tableInt[i][0]);
      if(tableInt[i][0]<10)printf(" ");
      printf("%d       ",tableInt[i][1]);
      if(tableInt[i][1]<10)printf(" ");
      printf("%s     ",table[i][0]);
      for(int j=0;j<(11-strlen(table[i][0]));j++){
        printf(" ");
      }
      printf("%s\n",table[i][1]);
  } */
}

static char* itostr(int d){
    char text[100] ;
    sprintf(text,"%d",d);
    char* r = text;
    return text;


}
static char* ftostr(double d){
    char text2[100] ;
    sprintf(text2,"%f",d);
    char* r = text2;
    return text2;

}
int  main(int  num_args , char** args) {
#if YYDEBUG == 1
 extern int yydebug;
yydebug = 1;
#endif
    if(num_args != 2) {
        printf("usage: ./ parser1  filename\n");
        exit (0);}FILE* file = fopen(args[1],"r");
        if(file == NULL) {
            printf("couldn ’t open %s\n", args [1]);
            exit (0);
        }
        signal(SIGSEGV,SIG_IGN);
        yyin = file;   // now  flex  reads  from  file
        yyparse ();
        //printTable();
        fclose(file);
}
